const PDFDocument = require("pdfkit");
const fs = require("fs");
const path = require("path");
const { promisify } = require("util");
const writeFileAsync = promisify(fs.writeFile);
const unlinkAsync = promisify(fs.unlink);

class PDFService {
  constructor() {
    this.tempDir = path.join(__dirname, "../temp");
    if (!fs.existsSync(this.tempDir)) {
      fs.mkdirSync(this.tempDir, { recursive: true });
    }
  }

  /**
   * Create PDF from HTML (using puppeteer for complex layouts)
   */
  async createPDFFromHTML(html, options = {}) {
    const puppeteer = require("puppeteer");

    const browser = await puppeteer.launch({
      headless: "new",
      args: ["--no-sandbox", "--disable-setuid-sandbox"],
    });

    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: "networkidle0" });

    const pdfBuffer = await page.pdf({
      format: options.format || "A4",
      margin: {
        top: options.marginTop || "50px",
        bottom: options.marginBottom || "50px",
        left: options.marginLeft || "50px",
        right: options.marginRight || "50px",
      },
      printBackground: true,
    });

    await browser.close();
    return pdfBuffer;
  }

  /**
   * Merge multiple PDFs
   */
  async mergePDFs(pdfBuffers) {
    const { PDFDocument } = require("pdf-lib");
    const mergedPdf = await PDFDocument.create();

    for (const buffer of pdfBuffers) {
      const pdf = await PDFDocument.load(buffer);
      const pages = await mergedPdf.copyPages(pdf, pdf.getPageIndices());
      pages.forEach((page) => mergedPdf.addPage(page));
    }

    return await mergedPdf.save();
  }

  /**
   * Add watermark to PDF
   */
  async addWatermark(pdfBuffer, watermarkText) {
    const { PDFDocument, rgb, StandardFonts } = require("pdf-lib");
    const pdfDoc = await PDFDocument.load(pdfBuffer);
    const pages = pdfDoc.getPages();
    const font = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    pages.forEach((page) => {
      const { width, height } = page.getSize();
      page.drawText(watermarkText, {
        x: width / 2 - 100,
        y: height / 2,
        size: 40,
        font: font,
        color: rgb(0.8, 0.8, 0.8),
        opacity: 0.3,
        rotate: Math.PI / 4,
      });
    });

    return await pdfDoc.save();
  }

  /**
   * Add cover page to PDF
   */
  async addCoverPage(pdfBuffer, coverData) {
    const { PDFDocument, rgb, StandardFonts } = require("pdf-lib");
    const pdfDoc = await PDFDocument.load(pdfBuffer);
    const coverPage = pdfDoc.insertPage(0);
    const { width, height } = coverPage.getSize();
    const font = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    // Add title
    coverPage.drawText(coverData.title || "AttendX Report", {
      x: width / 2 - 100,
      y: height - 100,
      size: 24,
      font: font,
      color: rgb(0.2, 0.2, 0.2),
    });

    // Add subtitle
    coverPage.drawText(coverData.subtitle || "", {
      x: width / 2 - 80,
      y: height - 140,
      size: 14,
      font: font,
      color: rgb(0.5, 0.5, 0.5),
    });

    // Add metadata
    const metaFont = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const metadata = [
      `Generated: ${new Date().toLocaleString()}`,
      `Generated by: ${coverData.generatedBy || "System"}`,
      `Report Type: ${coverData.reportType || "Standard Report"}`,
    ];

    metadata.forEach((text, index) => {
      coverPage.drawText(text, {
        x: 50,
        y: 100 + index * 20,
        size: 10,
        font: metaFont,
        color: rgb(0.3, 0.3, 0.3),
      });
    });

    return await pdfDoc.save();
  }

  /**
   * Clean up temporary files
   */
  async cleanup() {
    const files = fs.readdirSync(this.tempDir);
    for (const file of files) {
      const filePath = path.join(this.tempDir, file);
      const stats = fs.statSync(filePath);
      const now = new Date().getTime();
      const fileAge = now - stats.mtimeMs;

      // Delete files older than 1 hour
      if (fileAge > 3600000) {
        await unlinkAsync(filePath);
      }
    }
  }
}

module.exports = new PDFService();
